# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch

x = torch.rand(7,7)
print(x.shape)
print(x)

# Create random tensor


torch.Size([7, 7])
tensor([[8.6748e-02, 2.8286e-01, 7.4568e-01, 9.4455e-01, 5.2811e-01, 7.3100e-01,
         4.9314e-01],
        [9.0362e-01, 1.3959e-01, 8.8894e-01, 6.7748e-01, 7.4792e-01, 9.6355e-01,
         2.5268e-01],
        [5.9597e-01, 6.9298e-01, 2.6745e-04, 4.5222e-01, 4.2592e-02, 7.9539e-01,
         5.6843e-02],
        [9.7504e-01, 7.0534e-02, 9.5262e-02, 5.1024e-01, 5.5411e-01, 6.0614e-01,
         4.4409e-01],
        [8.9415e-01, 2.9333e-01, 5.6329e-01, 6.0932e-01, 4.9797e-01, 6.2749e-01,
         2.9081e-01],
        [7.9302e-01, 4.0465e-01, 9.6917e-01, 3.0928e-01, 5.0919e-01, 2.6127e-01,
         5.8687e-01],
        [8.5266e-01, 9.0467e-01, 5.1717e-01, 7.8452e-01, 6.4924e-01, 4.5446e-01,
         1.2848e-02]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
y = torch.rand(1, 7)
print(y.shape)
print(y)

y_prim = torch.reshape(y, (7, 1))
print(y_prim)

xy = torch.matmul(x, y_prim)
# Perform matrix multiplication 
print("\n", xy)

torch.Size([1, 7])
tensor([[0.5867, 0.3295, 0.8425, 0.4284, 0.7801, 0.6619, 0.2729]])
tensor([[0.5867],
        [0.3295],
        [0.8425],
        [0.4284],
        [0.7801],
        [0.6619],
        [0.2729]])

 tensor([[2.2073],
        [2.9054],
        [1.3471],
        [1.8488],
        [2.2400],
        [2.2779],
        [2.3809]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
RANDOM_SEED = 32

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(4, 5)
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(5, 4)
# Matrix multiply tensors
tensor_AB = torch.matmul(tensor_A, tensor_B)

print(tensor_AB.shape)
print(tensor_AB)


torch.Size([4, 4])
tensor([[1.8360, 1.1109, 1.5572, 1.0128],
        [1.4131, 0.9963, 1.3222, 0.7338],
        [2.6882, 1.4356, 2.5639, 1.7382],
        [1.4894, 1.1636, 1.7204, 0.6366]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
print(torch.max(tensor_AB))
# Find min
print(torch.min(tensor_AB))


tensor(2.6882)
tensor(0.6366)


### 9. Find the maximum and minimum index values of the output of 7.

In [19]:
# Find arg max
print(torch.argmax(tensor_AB))

# Find arg min
print(torch.argmin(tensor_AB))


tensor(8)
tensor(15)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [23]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_B = torch.squeeze(tensor_A)

# Print out tensors and their shapes
print(tensor_A.shape, '\n', tensor_A)
print()
print(tensor_B.shape, '\n', tensor_B)


torch.Size([1, 1, 1, 10]) 
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

torch.Size([10]) 
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
