In [50]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.1+cu117


In [51]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [52]:
# how many dimensions
scalar.ndim

0

In [53]:
# get python int
scalar.item()

7

In [54]:
# vector
vector = torch.tensor([7, 2])
vector

tensor([7, 2])

In [55]:
vector.ndim

1

In [56]:
vector.shape

torch.Size([2])

In [57]:
# matrix
matrix = torch.tensor([[1, 3],
                       [5, 3]])
matrix

tensor([[1, 3],
        [5, 3]])

In [58]:
matrix.ndim

2

In [59]:
matrix[1]

tensor([5, 3])

In [60]:
matrix[0]

tensor([1, 3])

In [61]:
matrix.size()

torch.Size([2, 2])

In [62]:
#########################################################################

In [63]:
matrix = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


In [64]:
matrix[0][2]

tensor(3)

In [65]:
#########################################################################

In [66]:
### Random tensors
random_tensor = torch.rand(3, 4)
random_tensor.shape

torch.Size([3, 4])

In [67]:
random_tensor.ndim

2

In [68]:
random_tensor

tensor([[0.0085, 0.1363, 0.4501, 0.6911],
        [0.7288, 0.3438, 0.6891, 0.0400],
        [0.0908, 0.4503, 0.3482, 0.1500]])

In [69]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.8133, 0.3403, 0.1953,  ..., 0.1212, 0.1507, 0.7314],
         [0.1647, 0.6059, 0.4312,  ..., 0.9029, 0.2302, 0.3263],
         [0.3951, 0.9097, 0.2328,  ..., 0.9728, 0.1297, 0.2061],
         ...,
         [0.9691, 0.5153, 0.5016,  ..., 0.7537, 0.2520, 0.2408],
         [0.1868, 0.0210, 0.7307,  ..., 0.5676, 0.0876, 0.8899],
         [0.8971, 0.6219, 0.0486,  ..., 0.5893, 0.8347, 0.5891]],

        [[0.2725, 0.4243, 0.0496,  ..., 0.2261, 0.7268, 0.9692],
         [0.6452, 0.0867, 0.7359,  ..., 0.9556, 0.9120, 0.0025],
         [0.7004, 0.1498, 0.4434,  ..., 0.0864, 0.6905, 0.3874],
         ...,
         [0.6084, 0.2768, 0.8923,  ..., 0.8873, 0.8793, 0.5742],
         [0.1215, 0.7134, 0.2554,  ..., 0.4635, 0.5004, 0.1753],
         [0.5046, 0.2982, 0.0524,  ..., 0.3349, 0.5059, 0.4207]],

        [[0.8401, 0.1835, 0.9357,  ..., 0.1124, 0.6855, 0.8762],
         [0.6800, 0.1792, 0.5844,  ..., 0.2957, 0.7200, 0.2165],
         [0.5369, 0.7281, 0.6476,  ..., 0.2087, 0.3795, 0.

In [70]:
random_image_size_tensor.ndim

3

In [71]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [72]:
#########################################################################
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [73]:
ones = torch.ones(2, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
#########################################################################

In [75]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
torch.arange(1, 5)

tensor([1, 2, 3, 4])

In [77]:
one_to_six = torch.arange(1, 7)
one_to_six

tensor([1, 2, 3, 4, 5, 6])

In [78]:
six_zeros = torch.zeros_like(one_to_six)
six_zeros

tensor([0, 0, 0, 0, 0, 0])

In [79]:
tensor.device


NameError: name 'tensor' is not defined

In [ ]:
six_zeros.device

In [ ]:
six_zeros.device("gpu")


In [ ]:
six_zeros.device = "gpu"

In [ ]:
six_zeros = torch.zeros_like(one_to_six, device="cpu")

In [ ]:
six_zeros

### Manipulating Tensors
* addition
* substraction
* multiplication
* division
* matrix operation

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

In [ ]:
tensor

In [ ]:
tensor = tensor + 2

In [ ]:
tensor

In [ ]:
tensor -2

In [ ]:
tensor - 4

In [ ]:
tensor


In [ ]:
tensor * 10


In [ ]:
tensor / 10


In [ ]:
################################################

tensor = torch.tensor([1, 2, 3])
tensor

In [ ]:
tensor * tensor

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)


In [ ]:
1 + 4 + 9


In [ ]:
################################################
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.matmul(tensor_a, tensor_b)

In [ ]:
torch.matmul(tensor_a, tensor_b.T)

In [ ]:
tensor_b.T

In [80]:
######################################################
# Tensor agregation

x = torch.arange(1, 10, 2)
x

tensor([1, 3, 5, 7, 9])

In [81]:
x.min()


tensor(1)

In [82]:
torch.min(x)

tensor(1)

In [83]:
torch.max(x), x.max()

(tensor(9), tensor(9))

In [84]:
x.type(torch.float32).mean()


tensor(5.)

### torch.mean() requries floating point number tensor

In [85]:
torch.mean(x.type(torch.float32))

tensor(5.)

In [86]:
x.argmax()

tensor(4)

In [87]:
x.max()

tensor(9)

In [88]:
x.argmin()

tensor(0)

In [89]:
x.min()

tensor(1)

In [90]:
x

tensor([1, 3, 5, 7, 9])

### Reshaping - reshapes input tensor to defined shape
### Stacking - combine multiple tensors on top of each other VSTACK or next to each other HSTACK'
### Squeeze - removes all 1 dimensioons from a tensor
### Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [114]:
import torch

x = torch.arange(1. , 11.)
print(x)
print(x.shape)

x_reshaped = x.reshape(1, 10)
print(x_reshaped)
print(x_reshaped.shape)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
torch.Size([10])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
torch.Size([1, 10])


In [122]:
x_reshaped = x.reshape(2, 5)
print(x_reshaped)
print(x_reshaped.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
torch.Size([2, 5])


In [126]:
# Changing view of matrix
z = x.view(1, 10)
print(z)
print(z.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
torch.Size([1, 10])


In [128]:
z[:, 0] = 69
print(z)
print(x)

tensor([[69.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
tensor([69.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [137]:
# Stacking:
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[69.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [69.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [69.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [152]:
# Squeezing and Unsqueezing
# squeezing removes all single dimensions from a tensor
x = torch.zeros(2,1,1)
print(x.size(), "\n")
print(x)

x_squeezed = torch.squeeze(x)
print(x_squeezed.size(), "\n")
print(x_squeezed)


torch.Size([2, 1, 1]) 

tensor([[[0.]],

        [[0.]]])
torch.Size([2]) 

tensor([0., 0.])


In [180]:
# Permuting
x = torch.rand(224, 224, 3)
print(x.shape)
x[0][0][0] = 777
x_permuted = x.permute(2, 0, 1)
print(x_permuted.shape)
# x_permuted


torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


### Indexing

In [189]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)

In [192]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [193]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [194]:
x[0][0]

tensor([1, 2, 3])

In [195]:
x[0, 0]

tensor([1, 2, 3])

In [200]:
x[0, 2, 2]

tensor(9)

In [203]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [204]:
x[:, :, 1]


tensor([[2, 5, 8]])

In [205]:
x[:, :, 2]


tensor([[3, 6, 9]])

In [209]:
x[0, 0, :]

tensor([1, 2, 3])

In [210]:
x[0, 2, 2]

tensor(9)

In [214]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [215]:
x[0, :, 2]

tensor([3, 6, 9])

### NumPy and PyTorch

In [217]:
import torch
import numpy as np

array = np.arange(1. , 8.)
print(array)
tensor = torch.from_numpy(array)
print(tensor)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


### Reproducbility

In [295]:
import torch 

tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

print(tensor_A)
print(tensor_B)


tensor([[0.2595, 0.6169, 0.2448, 0.4867],
        [0.2373, 0.0814, 0.2500, 0.9068],
        [0.6041, 0.5108, 0.6620, 0.3195]])
tensor([[0.4809, 0.2535, 0.7538, 0.3094],
        [0.5795, 0.7337, 0.1537, 0.3342],
        [0.3709, 0.8225, 0.1114, 0.0718]])


In [296]:
print(tensor_A == tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [310]:
RANDOM_SEED = 64

torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(3, 4)

print(tensor_C)
print(tensor_D)

print(tensor_C == tensor_D)


tensor([[0.0492, 0.5989, 0.1771, 0.2639],
        [0.4717, 0.8384, 0.1639, 0.1899],
        [0.9971, 0.5516, 0.7827, 0.1247]])
tensor([[0.0492, 0.5989, 0.1771, 0.2639],
        [0.4717, 0.8384, 0.1639, 0.1899],
        [0.9971, 0.5516, 0.7827, 0.1247]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [311]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [314]:
torch.cuda.is_available()

False

In [315]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [316]:
device

'cpu'